token: "lip_********************"
concurrency: 1                # Number of games to play simultaneously.
abort_time: 30                # Amount of time (in s) to abort game start after no activity.
move_overhead : 1000          # Amount of time (in ms) to subtract from each move before being given to the engine.
engine:
  path: /path/to/engine
  ponder: false
  fake_think: false           # Pretend to think instead of moving instantly (for limited search levels).
  uci_options:                # Arbitrary UCI options passed to the engine. Can be commented out or changed.
#    Threads: 1               # Max CPU threads the engine can use.
#    Hash: 128                # Hash size (in MB).

books:
  enabled: false
  selection: weighted_random  # One from weighted_random, uniform_random, or best_move.
  depth: 10
  standard:                   # List of book(s) for variant standard. Add additional books or variants.
    - books/standard_1.bin
    - books/standard_2.bin
  chess960:                   # List of book(s) for variant chess960.
    - books/chess960.bin

challenge:                    # Incoming challenges.
  enabled: true               # Flag for controlling if any challenges get accepted. Overrides all other flags.
  max_increment: 60           # Maximum amount of increment to accept a challenge. The max is 180. Set to 0 for no increment.
  min_increment: 0            # Minimum amount of increment to accept a challenge.
  max_initial: 3600           # Maximum amount of base time to accept a challenge. The max is 315360000 (10 years).
  min_initial: 0              # Minimum amount of base time to accept a challenge.
  variants:                   # Chess variants to accept (https://lichess.org/variant).
    - standard
#    - chess960
#    - fromPosition
#    - antichess
#    - atomic
#    - crazyhouse
#    - horde
#    - kingOfTheHill
#    - racingKings
#    - threeCheck
  time_controls:              # Time controls to accept (does not currently support correspondence).
    - bullet
    - blitz
    - rapid
    - classical
  modes:
    - casual
    - rated
  opponents:
    - human
    - bot
  max_rating_diffs:           # Maximum rating distance to opponent, useful for preventing elo manipulation.
    human: 600
    bot: 300

draw:                         # Whether to offer/accept draws under certain conditions.
  enabled: false
  score: 0                    # If engine score is less than or equal to this value, the bot offers/accepts draw (in cp).
  moves: 5                    # How many moves in a row the absolute value of the score has to be below the draw value.
  min_game_length: 35         # Only offer/accept a draw if the number of full moves on board is fewer than this value.

resign:
  enabled: false
  score: -900                 # If engine score is less than or equal to this value, the bot resigns (in cp).
  moves: 5                    # How many moves in a row the value of the score has to be below the resignation value.

matchmaking:
  enabled: true
  variant: standard
  initial_times:              # Initial time for matchmaking mode to be selected at random.
    - 60
    - 120
    - 180
    - 300
    - 480
    - 780
    - 1260
  increments:                 # Increment time for matchmaking mode to be selected at random.
    - 0
    - 1
    - 2
    - 3
    - 5
    - 8
    - 13
  max_rating_diff: 300        # Maximum rating distance to opponent.
  min_games: 20               # Minimum games opponent must have played in the chosen variant (including sub-division of standard into bullet, blitz etc.)
  timeout: 15                 # Timeout (in minutes) between nothing happening and issuing a challenge.
  rated: false                # Whether to challenge rated or casual.
